# Generated by django_user_permissions package – do not edit manually
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='Primary key of the target object. If null, permission applies to all objects of this content type.', null=True)),
                ('content_type', models.ForeignKey(help_text='Content type of the target object.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('permission', models.ForeignKey(help_text="Django permission (e.g., 'view_document', 'change_document').", on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(help_text='User who receives this permission.', on_delete=django.db.models.deletion.CASCADE, related_name='object_permissions', to='auth.user')),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'unique_together': {('user', 'permission', 'content_type', 'object_id')},
            },
        ),
    ]